### ISSUE TITLE
Alert: Could not authenticate you from PayPal because "Client validation error: invalid scope.".

### ISSUE THREAD

**Issue by brandondees** [datariot/omniauth-paypal#7]
We've had our app up and running in sandbox mode but when we went to switch out of sandbox mode and use the live API credentials, we started getting this error response: 

Alert: Could not authenticate you from PayPal because "Client validation error: invalid scope.".

PayPal's tech support is "looking into it" but hasn't been helpful yet. Their first suggestion was to use a file extension on the callback URLs, as in /auth/paypal.html which we are begrudgingly sorting out how to handle correctly on our server, in order to just test their hunch.

This is particularly frustrating since we are only receiving this response on our production server, not in any development or staging environments. The only difference is the domain name of our app and the use of Paypal's live credentials instead of sandbox credentials (and of course hitting paypal.com instead of sandbox.paypal.com, etc.)

Any clue would be helpful. Even if you know of a simple way to handle the url rewrites to test what tech support is suggesting, as we haven't discovered any way to override the callback url submitted to paypal through omniauth.

**Comment by lukepuplett** [comment]
Right. The PayPal app dashboard is just a shambles. The tick-boxes are presented in a way that has nothing to do with the scope or the documentation about the scope. For example, phone appears under address information but is listed as "phone" in the scope doc.

You also cannot untick the sub-options. The portal hangs or just doesn't save the changes. Always refresh and check again after making changes, chances are, you won't see them saved.

This might even be a cache convergence issue within PayPal. I don't know. I have no confidence in it at all. I couldn't even get the redirect URL to work until I had added privary and agreement links! Who knows what's going on behind the scenes. It's probably all corrupt.

The whole thing is FUBAR. When you make hundreds of millions a day, then of course your 12 page web empire is going to be crap. Why would you be trying to improve anything?

Complacency. Disruption. Tears. Blame. Move on. Next story card.

**Comment by datariot** [comment]
@lukepuplett sorry to hear this is still a problem :-/ I attribute most of my grey hairs to PayPal integration.

If only we could have used Stripe instead!

**Comment by lukepuplett** [comment]
Hello! Gosh that was a rant. Sorry. I found a bottle of Talisker on my desk this morning.

I'll scratch it and start over, I've read people having success with a new app and keys, obvs it must work somehow.

**Comment by schwannden** [comment]
Thank you @DSpeichert you are the man!

**Comment by pwalds** [comment]
Thanks, @DSpeichert, you saved the day.  Was pulling my hair out trying to figure it out and dug through a dozen forums until I got to this one.  That was it - make sure to set the scopes on the application side.

**Comment by Ycfx** [comment]
@DSpeichert it works like a charm , Thank you man !

**Comment by ingmferrer** [comment]
@DSpeichert 3 years later still THE answer!

**Comment by jackdneilson** [comment]
Sorry to bump such a dead topic, but I'm having a decent amount of trouble with paypal myself and I wondered if any of you gents could lend a hand.

I'm getting the same error, I'm trying to add permissions for the views in the paypal website dashboard but every time I try to save them it shows it's saved, then when I refresh the boxes are magically unticked. The permissions are definitely not being set because I'm still getting this stupid error 8 hours in. Any suggestions?

**Comment by GVRV** [comment]
@jackdneilson I vaguely remember having to ask PayPal support to enable certain things within the dashboard for me cause even though the dashboard UI reflected everything was fine, there are some other flag they had to enable.

**Comment by jackdneilson** [comment]
Thanks, I'll give it a shot. It's pretty crap that it doesn't even fail silently, it gives you a success message while failing in the background.
